serial_number: a300-00036
version: 0
system:
  username: robot
  hosts:
    - hostname: cpr-a300-00036
      ip: 192.168.131.1
  ros2:
    namespace: a300_00036
    domain_id: 0
    middleware:
      implementation: rmw_fastrtps_cpp
      discovery: server
      servers:
        - hostname: cpr-a300-00036
          port: 11811
          enabled: true
    workspaces:
    - "/home/robot/colcon_ws/install/setup.bash"
platform:
  battery:
    model: S_24V20_U1
    configuration: S1P2
  can_adapters:
    - can_dev: usbcan0
      type: serial
      serial_dev: /dev/usbcan
      baud: s5
  can_bridges:
    - interface: usbcan0
      topic_rx: sensors/charger_0/usbcan0/rx
      topic_tx: sensors/charger_0/usbcan0/tx
  attachments:
    - name: front_bumper
      type: a300.bumper
      parent: front_bumper_mount
    - name: rear_bumper
      type: a300.bumper
      parent: rear_bumper_mount
    - name: top_plate
      type: a300.top_plate
      model: pacs
      parent: default_mount
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
      enabled: true
    - name: wireless_charger
      type: a300.wireless_charger
      model: default
      parent: base_link
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
      enabled: true
  extras:
    urdf:
      package: mtu32_description
      path: urdf/robot_description.urdf.xacro
    launch:
      package: mtu32_bringup
      path: launch/swift_nav.launch.py
mounts:
  fath_pivot:
    - parent: top_plate_mount_c1
      xyz: [0.02, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
      angle: 0.0
sensors:
  charger:
    - model: wiferion
      urdf_enabled: true
      launch_enabled: true
      parent: wireless_charger_face
      xyz: [-0.003, 0.0, 0.01]
      rpy: [0.0, 3.14159, 0.0]
      ros_parameters:
        wiferion:
          canbus_dev: usbcan0
          launch_gateway: false
  imu:
    - model: microstrain_imu
      urdf_enabled: true
      launch_enabled: false
      parent: top_plate_mount_c2
      xyz: [0.0, 0.0, 0.01]
      rpy: [0.0, 0.0, 0.0]
      ros_parameters:
        microstrain_inertial_driver:
          imu_frame_id: imu_0_link
          port: /dev/microstrain_main
          use_enu_frame: true
  gps:
    - model: swiftnav_duro
      urdf_enabled: true
      launch_enabled: false
      parent: base_link
      xyz: [0.32479, 0.21329, 0.44735]
      rpy: [0.0, 0.0, 0.0]
      ros_parameters:
        duro_node:
          gps_receiver_frame_id: gps_0_link
          ip_address: 192.168.131.31
          ip_port: 55555
          imu_frame_id: gps_0_link
  lidar2d:
    - model: hokuyo_ust
      urdf_enabled: true
      launch_enabled: true
      parent: wireless_charger_lidar_mount
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
      ros_parameters:
        urg_node:
          laser_frame_id: lidar2d_0_laser
          ip_address: 192.168.131.20
          ip_port: 10940
          angle_min: -2.356
          angle_max: 2.356
  camera:
    - model: stereolabs_zed
      urdf_enabled: true
      launch_enabled: true
      parent: fath_pivot_0_mount
      xyz: [0.0, 0.0, 0.0]
      rpy: [0.0, 0.0, 0.0]
      ros_parameters:
        stereolabs_zed:
          general.grab_frame_rate: 30
          general.serial_number: 0
          general.camera_model: 'zed2'
          general.grab_resolution: 'AUTO'
manipulators:
  moveit:
    enable: true
  arms:
    - model: kinova_gen3_7dof
      parent: top_plate_mount_e9
      xyz: [0.0, 0.0, 0.0046]
      rpy: [0.0, 0.0, 3.14159]
      ip: 192.168.131.40
      port: 10000
      vision: true
      poses:
        - name: Ready
          joints: [0.0, -0.9, 0.0, 2.0, 0.0, 1.0, -1.571]
        - name: Forward
          joints: [0.0, 0.7, 0.0, -1.5, 0.0, -1.5, -1.571]
        - name: Straight
          joints: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.571]
        - name: Stow
          joints: [2.225, 1.3, 0.0, 1.75, -2.4, -1.65, -1.5]
      gripper:
        model: robotiq_2f_85
        xyz: [0.0, 0.0, 0.0]
        rpy: [0.0, 0.0, 0.0]
