/**/scan_to_scan_filter_chain:
  ros__parameters:
    box_filter:
      name: box_filter
      type: laser_filters/LaserScanBoxFilter
      params:
        box_frame: base_link
        max_x: 0.5
        max_y: 0.3
        max_z: 0.5
        min_x: -0.5
        min_y: -0.3
        min_z: -0.5        
        invert: false # activate to remove all points outside of the box
    speckle_filter:
      name: speckle_filter
      type: laser_filters/LaserScanSpeckleFilter
      params:
        filter_type: distance
        max_range: 2.0
        max_range_difference: 0.1
        filter_window: 2 # Remove points that don't have at least 2 neighbors
