/*/docking_server:
  ros__parameters:
    controller_frequency: 50.0
    initial_perception_timeout: 5.0
    wait_charge_timeout: 5.0
    dock_approach_timeout: 30.0
    undock_linear_tolerance: 0.05
    undock_angular_tolerance: 0.1
    max_retries: 3
    base_frame: "base_link"
    fixed_frame: "odom"
    odom_topic: "odom"
    odom_duration: 0.3
    dock_backwards: false  # Deprecated, use dock_direction in plugin
    dock_prestaging_tolerance: 0.5
    introspection_mode: "disabled"

    # Types of docks
    dock_plugins: ['simple_charging_dock']
    simple_charging_dock:
      plugin: 'opennav_docking::SimpleChargingDock'  # Also 'opennav_docking::SimpleNonChargingDock'
      docking_threshold: 0.05
      staging_x_offset: -0.7
      use_external_detection_pose: true
      detector_service_name: '/detector/toggle'
      detector_service_timeout: 5.0
      subscribe_toggle: true
      use_battery_status: false # true
      use_stall_detection: false
      rotate_to_dock: false

      external_detection_timeout: 1.0
      external_detection_translation_x: -0.18
      external_detection_translation_y: 0.0
      external_detection_rotation_roll: -1.57
      external_detection_rotation_pitch: -1.57
      external_detection_rotation_yaw: 0.0
      filter_coef: 0.1
      dock_direction: "forward" # "backward"

    controller:
      k_phi: 3.0
      k_delta: 2.0
      v_linear_min: 0.15
      v_linear_max: 0.15
      v_angular_max: 0.75
      slowdown_radius: 0.25
      rotate_to_heading_angular_vel: 1.0
      rotate_to_heading_max_angular_accel: 3.2
      use_collision_detection: true
      costmap_topic: "local_costmap/costmap_raw"
      footprint_topic: "local_costmap/published_footprint"
      transform_tolerance: 0.1
      projection_time: 1.0
      simulation_time_step: 0.1
      dock_collision_threshold: 0.3

    docks: ["charging_1"]
    charging_1:
      type: "husky_dock"
      frame: "map"
      pose: [-1.45, 0.48, 0.0]